- name: Install NGINX Ingress Controller ( all tasks on control-plane node )
  copy:
    src: ingress-nginx.yaml 
    dest: /tmp/ingress-nginx.yaml
  changed_when: false

- name: Apply NGINX Ingress Controller 
  command: kubectl apply -f /tmp/ingress-nginx.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false

- name: Wait for ingress controller to be ready
  command: kubectl -n ingress-nginx rollout status deployment ingress-nginx-controller
  register: ingress_ready
  retries: 30
  delay: 6
  until: ingress_ready.rc == 0
  changed_when: false
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Wait for ingress external IP
  command: kubectl get svc -n ingress-nginx ingress-nginx-controller
  register: ingress_svc
  retries: 30
  delay: 5
  until: ingress_svc.stdout is not search("<pending>")
  changed_when: false
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf    



- name: Check status of NGINX Ingress services
  command: kubectl get svc -n ingress-nginx
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: nginx_ingress_status

- name: Display NGINX Ingress services status
  debug:
    msg: "{{ nginx_ingress_status.stdout }}"    
  
