- name: Copy Calico manifest (VXLAN)
  copy:
    src: calico.yaml
    dest: /tmp/calico.yaml
  when: "'master' in group_names"

- name: Apply Calico
  command: kubectl apply -f /tmp/calico.yaml
  when: "'master' in group_names"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

# --- WAIT NA CALICO ---
- name: Wait for Calico pods to be Running
  command: kubectl get pods -n kube-system
  register: calico_status
  retries: 30
  delay: 5
  until: calico_status.stdout is search("calico-node") and calico_status.stdout is search("Running")
  changed_when: false
  when: "'master' in group_names"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

# --- WAIT NA NODE READY ---
- name: Wait for all nodes to be Ready
  command: kubectl get nodes --no-headers
  register: all_nodes
  retries: 30
  delay: 6
  until: >
    all_nodes.stdout_lines | length > 0 and
    (all_nodes.stdout_lines | select("search", " Ready ") | list | length)
    ==
    (all_nodes.stdout_lines | length)
  changed_when: false
  when: "'master' in group_names"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Display node status
  debug:
    msg: "{{ all_nodes.stdout }}"
  when: "'master' in group_names"

# --- GENERATE JOIN ---
- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command_raw
  when: "'master' in group_names"

# --- SAVE DO HOSTVARS ---
- name: Set join command fact
  set_fact:
    kube_join_cmd: "{{ join_command_raw.stdout }}"
  when: "'master' in group_names"

# --- DEBUG (opcjonalnie)
- name: Show join command
  debug:
    msg: "{{ kube_join_cmd }}"
  when: "'master' in group_names"

# --- JOIN WORKERS --- Stary dzialajacy ale przy kolejnym RUNie sie wysypie
#- name: Join workers to cluster
#  command: "{{ hostvars[groups['master'][0]].kube_join_cmd }} --ignore-preflight-errors=all"
#  when: "'workers' in group_names"

# --- JOIN WORKERS (IDEMPOTENT) ---

# NOWE — sprawdzamy czy node już jest w clusterze
- name: Check if node already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf


#  POPRAWIONE — join tylko jeśli node NIE jest w clusterze
- name: Join workers to cluster
  command: "{{ hostvars[groups['master'][0]].kube_join_cmd }} --ignore-preflight-errors=all"
  when:
    - "'workers' in group_names"
    - not kubelet_conf.stat.exists
    - hostvars[groups['master'][0]].kube_join_cmd is defined


#  NOWE (opcjonalne — lepsze logi)
- name: Skip join (already part of cluster)
  debug:
    msg: "Node already joined, skipping"
  when:
    - "'workers' in group_names"
    - kubelet_conf.stat.exists


# --- WAIT NA WORKERS ---
- name: Wait for all nodes to be Ready
  command: kubectl get nodes --no-headers
  register: all_nodes
  retries: 30
  delay: 6
  until: >
    all_nodes.stdout_lines | length > 0 and
    (all_nodes.stdout_lines | select("search", " Ready ") | list | length)
    ==
    (all_nodes.stdout_lines | length)
  changed_when: false
  when: "'master' in group_names"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

# --- METALLB ---
- import_tasks: metallb.yml
  when: "'master' in group_names"
