- name: Install Helm dependecies
  package:
    name:
      - curl
      - openssl
    state: present
  when: helm_install_host_var
      
- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'  
  when: helm_install_host_var

- name: Install Helm
  command: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm
  when: helm_install_host_var

- name: Add Prometheus Helm repo
  command: /usr/local/bin/helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  register: helm_repo_add
  changed_when: "'already exists' not in helm_repo_add.stderr"
  when: helm_install_host_var

- name: Update Helm repos
  command: /usr/local/bin/helm repo update
  changed_when: false
  when: helm_install_host_var
