---
- name: Import tasks for Rocky Linux nodes
  import_tasks: rocky.yml
  when: ansible_os_family == "RedHat"


- name: Import tasks for Ubuntu Linux nodes
  import_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"


- name: Disable swap on all nodes swampoff -a
  become: true
  ansible.builtin.command: swapoff -a
  

- name: Ensure swap is disabled on all nodes in fstab
  become: true
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^\S+\s+\S+\s+swap\s+.*$'
    replace: ''