---
- name: Reset workers before join
  hosts: workers
  become: true

  tasks:
    - name: Reset previous kubeadm state
      shell: kubeadm reset -f
      ignore_errors: yes

    - name: Join node to cluster
      shell: |
        sudo kubeadm join 192.168.0.100:6443 --token 8ksqba.i8xl00f4ljgugtk1 --discovery-token-ca-cert-hash sha256:71d5663b88b56ad2dfd846822bfaa7e9e62332b5b8562adab188324354c7a4ff
