- import_tasks: rocky.yml
  when: ansible_os_family == "RedHat"

- import_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Create registry config directory
  file:
    path: "/etc/containerd/certs.d/{{ registry_ip }}:5000"
    state: directory
    mode: '0755'

- name: Configure insecure registry
  copy:
    dest: "/etc/containerd/certs.d/{{ registry_ip }}:5000/hosts.toml"
    content: |
      server = "http://{{ registry_ip }}:5000"

      [host."http://{{ registry_ip }}:5000"]
        capabilities = ["pull", "resolve"]
        plain_http = true
  notify: restart containerd
